// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlOrKQLfx8McSsRtyrRTbeJ4M-CkRg_-I',
    appId: '1:306087285:web:0bc6f6f66b5cad3156bf3c',
    messagingSenderId: '306087285',
    projectId: 'cactus0201',
    authDomain: 'cactus0201.firebaseapp.com',
    storageBucket: 'cactus0201.firebasestorage.app',
    measurementId: 'G-HCG954HD4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX692kSARNXoM84m7GT74lyTx0nZdRF5o',
    appId: '1:306087285:android:b0ad8d0f5aabf34156bf3c',
    messagingSenderId: '306087285',
    projectId: 'cactus0201',
    storageBucket: 'cactus0201.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX9vU_1-lq0EeZWQajCpsYbU2l7pwtNKs',
    appId: '1:306087285:ios:5c3c2518b9b014f256bf3c',
    messagingSenderId: '306087285',
    projectId: 'cactus0201',
    storageBucket: 'cactus0201.firebasestorage.app',
    iosBundleId: 'com.shloknaik.cactus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX9vU_1-lq0EeZWQajCpsYbU2l7pwtNKs',
    appId: '1:306087285:ios:070e7d6f0114437556bf3c',
    messagingSenderId: '306087285',
    projectId: 'cactus0201',
    storageBucket: 'cactus0201.firebasestorage.app',
    iosBundleId: 'com.example.book',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlOrKQLfx8McSsRtyrRTbeJ4M-CkRg_-I',
    appId: '1:306087285:web:a3e538975806672256bf3c',
    messagingSenderId: '306087285',
    projectId: 'cactus0201',
    authDomain: 'cactus0201.firebaseapp.com',
    storageBucket: 'cactus0201.firebasestorage.app',
    measurementId: 'G-MTVBZPY9GT',
  );
}
